name: safebox
title: SafeBox
base: core24
version: '1.3.1'
summary: Bubblewrap ve MATE tabanli guvenli sanal masaustu
description: |
  SafeBox, Linux uzerinde guvenilmeyen dosyalari calistirmak, 
  guvenli web gezintisi yapmak ve sistemi kalintilardan korumak icin 
  Bubblewrap altyapisini kullanan hafif, izole bir MATE sanal masaustu ortamidir.
license: GPL-3.0
contact: https://github.com/winexee/safebox

grade: stable
confinement: strict

apps:
  safebox:
    command: usr/bin/safebox
    desktop: usr/share/applications/safebox.desktop
    extensions: [gnome]
    plugs:
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - unity7
      - network
      - network-bind
      - home
      - opengl
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      GI_TYPELIB_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$SNAP/usr/lib/girepository-1.0:$GI_TYPELIB_PATH

parts:
  safebox:
    plugin: dump
    source: .
    stage-packages:
      - bubblewrap
      - xserver-xephyr
      - mate-desktop-environment-core
      - dbus-x11
      - python3-gi
      - gir1.2-gtk-3.0
      - x11-xserver-utils
      - python3
